### ISSUE TITLE
probability prediction map crop

### ISSUE THREAD

**Issue by cloudyliy** [QuangBK/drusen_seg#1]
How does the probability prediction map obtained by the image-level network correspond to the original image according to the corresponding position and crop it? Is there no code for this part in the Repository?

**Comment by QuangBK** [comment]
Hello,
I did update the code for cropping.

- For predicting the probability map by the image-level network, you can check the notebook [test_segmentation_Deep_lab.ipynb](https://github.com/QuangBK/drusen_seg/blob/master/test_segmentation_Deep_lab.ipynb)
- For cropping images and drusen mask, please check the notebook [patch_extract.ipynb](https://github.com/QuangBK/drusen_seg/blob/master/patch_extract.ipynb).

**Comment by cloudyliy** [comment]
Dear QuangBK,
Thank you very much for improving this part of the code. Another question is how to leave the marked image blocks for training when selecting the patch, and remove the image blocks that are all background. Is it artificially selected?&nbsp;
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "QuangBK"<notifications@github.com&gt;; 
发送时间: 2020年10月6日(星期二) 晚上10:40
收件人: "QuangBK/drusen_seg"<drusen_seg@noreply.github.com&gt;; 
抄送: "LIY"<2659678835@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QuangBK/drusen_seg] probability prediction map crop (#1)





 
Hello,
 I did update the code for cropping. Please check the notebook patch_extract.ipynb.

**Comment by QuangBK** [comment]
I believe you are referring to this part of the paper:
> "To avoid all background samples, we only select the patches including at least one pixel as drusen."

If so, please check this line in [patch_extract.ipynb](https://github.com/QuangBK/drusen_seg/blob/master/patch_extract.ipynb):
`if img_gray_mask[i:i+PATCH_SIZE, j:j+PATCH_SIZE].sum() > PATCH_SIZE*PATCH_SIZE/2 and mask_cropped[i:i+PATCH_SIZE, j:j+PATCH_SIZE].sum() > 0:`

We only crop the patches with at least one pixel as drusen by setting `mask_cropped[i:i+PATCH_SIZE, j:j+PATCH_SIZE].sum() > 0`

**Comment by cloudyliy** [comment]
I understand, thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "QuangBK"<notifications@github.com&gt;; 
发送时间: 2020年10月7日(星期三) 下午3:23
收件人: "QuangBK/drusen_seg"<drusen_seg@noreply.github.com&gt;; 
抄送: "LIY"<2659678835@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QuangBK/drusen_seg] probability prediction map crop (#1)





 
I believe you are referring to this part of the paper:
  
"To avoid all background samples, we only select the patches including at least one pixel as drusen."
  
If so, please check this line in patch_extract.ipynb:
 if img_gray_mask[i:i+PATCH_SIZE, j:j+PATCH_SIZE].sum() &gt; PATCH_SIZE*PATCH_SIZE/2 and mask_cropped[i:i+PATCH_SIZE, j:j+PATCH_SIZE].sum() &gt; 0:
 
We only crop the patches with at least one pixel as drusen by setting mask_cropped[i:i+PATCH_SIZE, j:j+PATCH_SIZE].sum() &gt; 0
